<?php

namespace ContainerQgPSxYP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G6U4b5UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.g6U4b5U' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g6U4b5U'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'artiste' => ['services', 'App\\Entity\\Artiste', 'getArtisteService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'artiste' => 'App\\Entity\\Artiste',
            'manager' => '?',
        ]);
    }
}
