<?php

namespace ContainerQgPSxYP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArtisteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Entity\Artiste' shared autowired service.
     *
     * @return \App\Entity\Artiste
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Entity'.\DIRECTORY_SEPARATOR.'Artiste.php';

        return $container->services['App\\Entity\\Artiste'] = new \App\Entity\Artiste();
    }
}
