<?php

namespace ContainerQJjLrBE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_75N9Wt6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.75N9Wt6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.75N9Wt6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'repo' => ['privates', 'App\\Repository\\StyleRepository', 'getStyleRepositoryService', true],
        ], [
            'paginator' => '?',
            'repo' => 'App\\Repository\\StyleRepository',
        ]);
    }
}
