<?php

namespace ContainerQJjLrBE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JsQYJf6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jsQYJf6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jsQYJf6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'style' => ['privates', '.errored..service_locator.jsQYJf6.App\\Entity\\Style', NULL, 'Cannot autowire service ".service_locator.jsQYJf6": it references class "App\\Entity\\Style" but no such service exists.'],
        ], [
            'manager' => '?',
            'style' => 'App\\Entity\\Style',
        ]);
    }
}
