<?php

namespace ContainerQJjLrBE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Px8MtKDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.px8MtKD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.px8MtKD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'album' => ['privates', '.errored..service_locator.px8MtKD.App\\Entity\\Album', NULL, 'Cannot autowire service ".service_locator.px8MtKD": it references class "App\\Entity\\Album" but no such service exists.'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'album' => 'App\\Entity\\Album',
            'manager' => '?',
        ]);
    }
}
