<?php

namespace ContainerQJjLrBE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStyleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jsQYJf6.App\Entity\Style' shared service.
     *
     * @return \App\Entity\Style
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jsQYJf6": it references class "App\\Entity\\Style" but no such service exists.');
    }
}
