<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQJjLrBE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQJjLrBE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQJjLrBE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQJjLrBE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQJjLrBE\App_KernelDevDebugContainer([
    'container.build_hash' => 'QJjLrBE',
    'container.build_id' => '9363f923',
    'container.build_time' => 1696759438,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQJjLrBE');
